# Generated by Django 5.0.6 on 2024-06-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveBigIntegerField()),
                ('image', models.ImageField(upload_to='room_img')),
                ('type', models.CharField(choices=[('single bed', 'single bed'), ('double bed', 'double bed'), ('twin bed', 'twin bed'), ('king suite', 'king suite'), ('queen suite', 'queen suite'), ('two bedroom suite', 'two bedroom suite'), ('junior suite', 'junior suite'), ('presidential suite', 'presidential suite')], max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
