# Generated by Django 5.0.6 on 2024-06-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rooms_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='type',
            field=models.CharField(choices=[('standard room', 'standard room'), ('deluxe room', 'deluxe room'), ('suite room', 'suite room'), ('connecting room', 'connecting room')], max_length=100),
        ),
    ]
