# Generated by Django 5.0.6 on 2024-07-13 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_image_rooms_image1_rooms_image2_rooms_image3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('standard room', 'standard room'), ('deluxe room', 'deluxe room'), ('suite room', 'suite room'), ('connecting room', 'connecting room')], max_length=100)),
                ('amenities', models.TextField(max_length=1000)),
                ('bathroom', models.TextField(max_length=1000)),
                ('special_features', models.TextField(max_length=1000)),
                ('policies', models.TextField(max_length=1000)),
                ('additional_info', models.TextField(max_length=1000)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.rooms')),
            ],
        ),
    ]
