# Generated by Django 5.0.6 on 2024-07-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_roomdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='additional_info',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='rooms',
            name='amenities',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='rooms',
            name='bathroom',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='rooms',
            name='policies',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='rooms',
            name='special_features',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='RoomDetails',
        ),
    ]
