# Generated by Django 5.0.6 on 2024-07-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_booking_address_alter_booking_check_in_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='type',
            field=models.CharField(blank=True, choices=[('standard room', 'standard room'), ('deluxe room', 'deluxe room'), ('suite room', 'suite room'), ('connecting room', 'connecting room')], max_length=100),
        ),
    ]
