# Generated by Django 5.0.6 on 2024-07-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_booking_check_in_date_remove_booking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='type',
            field=models.CharField(choices=[('standard room', 'standard room'), ('deluxe room', 'deluxe room'), ('suite room', 'suite room'), ('connecting room', 'connecting room')], max_length=100),
        ),
    ]
