# Generated by Django 5.0.6 on 2024-07-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_booking_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
