# Generated by Django 5.0.6 on 2024-07-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_booking_check_in_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='price',
            new_name='rent',
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
